
pipeline {
    agent any
    tools{ jdk 'JDK11' }
    environment {
        DOCKER_TAG = getVersion()
}
stages {
stage ('Clone Stage') {
steps {
git  'https://github.com/MedBilelAbidi/datacamp_docker_angular.git'
}
}
stage ('Docker Build') {
 steps {
 sh 'docker build -t mohamed311/astnvilla:${DOCKER_TAG}.'
 }
 }
}
}
def getVersion(){
def version = sh returnStdout: true, script: 'git rev-parse --short HEAD'
return version
}
